name: Set up Golang

on:
  workflow_call:
    inputs:
      go-version:
        description: "The version of node to use"
        required: false
        type: string
        default: "latest"

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v4
        name: ğŸ”§ Set up Node.js
        with:
          node-version: 'latest'
      - uses: actions/setup-go@v5
        name: ğŸ”§ Set up Go ${{ inputs.go-version }}
        with:
          go-version:  ${{ inputs.go-version }}

      - name: ğŸ“¦ Install dependencies
        run: |
          go get .
          go install github.com/ctrf-io/go-ctrf-json-reporter/cmd/go-ctrf-json-reporter@latest

      - name: ğŸ” Test with the Go CLI
        run: go test -json ./... | go-ctrf-json-reporter -output ctrf-report.json

      - name: ğŸ“ Publish CTRF Test Summary Results
        run: npx github-actions-ctrf ctrf-report.json
        if: always()

      - name: âŒ Publish CTRF Failed Test Summary Results
        run: npx github-actions-ctrf failed ctrf-report.json
        if: always()

      - run: npx semantic-release --dry-run
        name: ğŸ§® Get next version number
        id: get-next-version
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
